### ISSUE TITLE
Error uploading photos from a normal user account

### ISSUE THREAD

**Issue by maxlinux2000** [sbrajesh/buddyblog#11]
HI,

I just installed this great plugin and all works as expected, as admin.
But when I try with a normal user account I can only publish and edit the Post entry, but not upload a simple 200kb photo.
No other error in the console.

![xbuddyblog](https://cloud.githubusercontent.com/assets/5683921/17337852/dcb4529c-58e4-11e6-8134-0d68b88ea63b.png)

I think that the problem is coming form the user media permission. Please have a look here.

![xbuddyblog2](https://cloud.githubusercontent.com/assets/5683921/17337919/2bb679ce-58e5-11e6-96c5-a4c8283970b1.png)

tnx
MaX

**Comment by sbrajesh** [comment]
Closing due to age of ticket. It has been fixed since originally reported.
