### ISSUE TITLE
Error Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by seevidyadhar** [sbrajesh/buddyblog#12]
Hi, I am using wordpress 4.5+ and Buddypress 2.6+
When I activated Buddyblog I am receiving following error
Notice: Trying to get property of non-object in /home/vasudeo/public_html/wp-content/plugins/buddyblog/core/filters.php on line 192
Please help. 
this plugin is very usefull to me

**Comment by sbrajesh** [comment]
Closing due to age of the ticket.
