### ISSUE TITLE
permalinks structure

### ISSUE THREAD

**Issue by justinab** [sbrajesh/buddyblog#3]
For any member post, I now have permalink http://example.com/my-custom-post-type-slug/post-name-slug/
However, because of specialty of my site, members post blog posts with the exact same titles (as the title is the name of specific events that my website is all about). So I get hundreds of same slugs, just with the 1, 2, 3, ... added, as per standard WP behavior. 
What I would like is at least to include member's name into slug. Ideal would be also, if possible, to add a taxonomy slug (as my custom post type I use for BuddyBlog has taxonomies too). 
Can you help me here, or at least point to the correct direction?

**Comment by sbrajesh** [comment]
This is now available in the admin settings.
