### ISSUE TITLE
No admin / settings?

### ISSUE THREAD

**Issue by angeliquejw** [sbrajesh/buddyblog#4]
I'm using WP 3.6.1 and BP 1.8.1. After installing BuddyBlog and BP Simple Front End, the basic functionality of the plugin works, but I don't get any of the options/settings on the dashboard (either in their own tab or under Settings). Trying to tweak the code now and figure out what's wrong, but thought I'd post the issue.

**Comment by thomasklosinsky** [comment]
Hi angelique,

I think there are no settings to be made so there is no section for that.
...

**Comment by sbrajesh** [comment]
Updating old ticket. Version 1.1 ads an admin settings page which can be used to tune all settings.
