### ISSUE TITLE
Choose categories to restrict users

### ISSUE THREAD

**Issue by thomasklosinsky** [sbrajesh/buddyblog#5]
Sorry, this is not a real issue but a feature request.
Would it be easily possible to implement a category restriction for frontend users to blog in?

**Comment by thomasklosinsky** [comment]
would this be possible with the here decribed custom post type?
http://buddydev.com/buddypress/introducing-buddyblog-allow-users-to-blog-from-their-buddypress-profile/
But I can't see a setting for:
'category'= 14,12 // using comma separated category IDs for the post to automatically apply categories

Any chance?

**Comment by sbrajesh** [comment]
Sorry, closing due to age of ticket.
