### ISSUE TITLE
Blog post goes to main site instead of own site

### ISSUE THREAD

**Issue by rhisss** [sbrajesh/buddyblog#6]
Using with WP 4.1 Multisite, BP2.2

An non-admin user posts a blog from profile and expects this to be deposited under his own blog/site.
But the post goes to the main site which is owned by the admin.
The p2 theme has a similar blog posting front-end form - there this problem is not there using the same set-up.

**Comment by sbrajesh** [comment]
Sorry for being too late here. this plugin does not server that purpose for multisite. The only goal it servers is allow users to edit/post/delete posts from profile on the site where BuddyPress is active(Main BuddyPress site). It is not meant for managing blog posts in multisite environment for individual blogs of the user.
